development:
  adapter: postgresql
  encoding: unicode
  database: ambiente_development
  host: localhost
  pool: 5
  username: ianobraczka
  password: 010595

test:
  adapter: postgresql
  encoding: unicode
  database: ambiente_test
  host: localhost
  pool: 5
  username: ianobraczka
  password: 010595

production:
  adapter: postgresql
  encoding: unicode
  database: ambiente_production
  host: localhost
  pool: 5
  username: ianobraczka
  password: 010595